SUB1

// Maint, Security, and Assault bots share damage sounds, and
// Security and Assault bots use the same schema, so must combine
// them all under a single description.

{
	type "bark"
	descr "Bot"
	sub md1amb_1 { text "Zeitweilige Gefahr entdeckt." }
	sub md1amb_2 { text "Versuche, Selbstreparatur durchzufhren." }
	sub md1amb_3 { text "Gefahr. Warnung." }
	sub md1amb_4 { text "M”gliche Anomalie in diesem Gebiet." }
	sub md1amb_5 { text "Selbstdiagnose wird gestartet." }
//	
	sub md1at0_1 { text "Diagnosedisk wird gestartet." }
//
	sub md1at0_2 { text "Deckverkleidungsstabilit„t nominal." }
	sub md1at0_3 { text "Zu viel Schrott festgestellt. Aufr„umteam wird gerufen." }
	sub md1at0_4 { text "Batterien fast leer. Hydraulikflssigkeit ausreichend. Servomechanismen aktiv." }
	sub md1at2_1 { text "Best„tigung wird angestrebt." }
	sub md1at2_2 { text "Zusatzsensoren aktiv." }
	sub md1at2_3 { text "Entdeckungsspektrum verkleinert." }
	sub md1at2_5 { text "Zielaufl”sung nimmt zu." }
	sub md1at3_1 { text "Ziel auáer Reichweite." }
	sub md1at3_2 { text "Zielerfassung inkorrekt." }
	sub md1at3_3 { text "Erneute Zielerfassung. Erneute Zielerfassung." }
	sub md1at3_4 { text "Sensorenkontakt verloren." }
	sub md1at3_5 { text "Lokalisierung nicht erfolgreich." }
	sub md1att_1 { text "Gefahr wird neutralisiert." }
	sub md1att_2 { text "Notwartung wird durchgefhrt." }
	sub md1att_3 { text "Organische Gefahr entdeckt." }
	sub md1att_4 { text "Entfernung gestartet." }
	sub md1att_5 { text "Organische Anomalie wird entfernt." }
	sub md1bak_1 { text "Kein weiterer Input festgestellt." }
	sub md1bak_2 { text "Anomalie wurde nicht wiederholt." }
	sub md1bak_3 { text "Keine Einheiten festgestellt." }
	sub md1bak_4 { text "Diskrepanz kann vernachl„ssigt werden." }
	sub md1bak_5 { text "Beobachtung ohne Erfolg." }
	sub md1bod_1 { text "Einheit funktionsunf„hig." }
	sub md1bod_2 { text "Groáe Gefahr in diesem Gebiet." }
	sub md1bod_3 { text "Gefahrenanomalie fnfter Klasse." }
	sub md1bod_4 { text "Einheit wurde absichtlich besch„digt." }
	sub md1bod_5 { text "Suche nach m”glichen Gefahren." }
	sub md1chg_1 { text "Schutt erweist sich als feindlich. Laser aktivert." }
	sub md1chg_2 { text "Aufr„umungsroutine gestartet." }
	sub md1chg_3 { text "Schuttr„umung gestartet." }
	sub md1los_1 { text "Wartung nicht abgeschlossen." }
	sub md1los_2 { text "Zielerfassung weiterhin nicht erfolgreich." }
	sub md1los_3 { text "Erfassung erfolglos." }
	sub md1los_4 { text "Sensoreninput innerhalb der Standardwerte." }
	sub md1los_5 { text "Anomalie nicht mehr in der N„he." }
	sub md1to1_1 { text "Inputprozess wiederholt." }
	sub md1to1_2 { text "M”gliche Anomalie." }
	sub md1to1_3 { text "Beobachtung gestartet." }
	sub md1to1_4 { text "Abnormales Detail beobachtet." }
	sub md1to1_5 { text "Frage: Andere Einheiten?" }
	sub md1to2_1 { text "Input verarbeitet: mit Ergebnis." }
	sub md1to2_2 { text "Input verglichen: Keine šbereinstimmung." }
	sub md1to2_3 { text "Diskrepanz ist signifikant." }
	sub md1to2_4 { text "Anomalie festgestellt." }
	sub md1to2_5 { text "Beobachtung wird fortgesetzt." }
	sub md1to3_1 { text "Bewegte Bruchstcke in Sensorenreichweite." }
	sub md1to3_2 { text "Aktive Diskrepanz erfasst." }
	sub md1to3_3 { text "Organische Anomalie entdeckt." }
	sub md1to3_4 { text "Diskrepanz eindeutig klassifiziert." }
	sub md1to3_5 { text "Unzul„ssiger Input lokalisiert." }
	sub sd1amb_1 { text "Xerxes, nicht erfasster Feind." }
	sub sd1amb_2 { text "Xerxes, unbekannter Feind an dieser Position." }
	sub sd1at0_1 { text "Xerxes, bitte um erneuten Aufruf der šberwachungskameradatenbank." }
	sub sd1at0_2 { text "Verstanden. Weitere Anweisungen?" }
	sub sd1at0_3 { text "Xerxes, irgendwelche Aktivit„ten?" }
	sub sd1at0_4 { text "Sichtlinie nicht optimal. Xerxes, Wartungseinheiten sollen dies verbessern." }
	sub sd1at2_1 { text "Xerxes, noch nicht eindeutig identifiziert." }
	sub sd1at2_2 { text "Xerxes, Ziel ist schwer erfassbar." }
	sub sd1at2_3 { text "Xerxes, Anomalie wird n„her untersucht." }
	sub sd1at2_4 { text "Xerxes, Aufnahme begonnen." }
	sub sd1at2_5 { text "Xerxes, noch keine Aktion gegen Ziel durchgefhrt." }
	sub sd1at3_1 { text "Xerxes, Ziel ist vom Radar verschwunden." }
	sub sd1at3_2 { text "K”nnen Sie Ziel lokalisieren, Xerxes?" }
	sub sd1at3_3 { text "Xerxes, keine visuelle Zielerfassung mehr." }
	sub sd1at3_4 { text "Xerxes, Zielerfassung versagt." }
	sub sd1at3_5 { text "Eindringling ist Sensorerfassung entkommen, Xerxes" }
	sub sd1att_1 { text "Greife Feind an." }
	sub sd1att_2 { text "Aktiviere Offensivmaánahmen." }
	sub sd1att_3 { text "Xerxes, best„tigen." }
	sub sd1att_4 { text "Ziel erfasst." }
	sub sd1att_5 { text "Neutralisiere Ziel." }
	sub sd1bak_1 { text "Nein, Xerxes." }
	sub sd1bak_2 { text "Keine weiteren Inputs korreliert, Xerxes." }
	sub sd1bak_3 { text "Xerxes, keine weitere Aktivit„t." }
	sub sd1bak_4 { text "Xerxes, nichts erfasst." }
	sub sd1bak_5 { text "Xerxes, falscher Alarm." }
	sub sd1bod_1 { text "Xerxes, Einheit 34-J ist defekt." }
	sub sd1bod_2 { text "Xerxes, feindliche Aktion best„tigt." }
	sub sd1bod_3 { text "Einheit 72-J funktionsunf„hig. Bitte best„tigen." }
	sub sd1bod_4 { text "Xerxes, Einheit vernichtet." }
	sub sd1bod_5 { text "Xerxes, Eindringling ist feindselig." }
	sub sd1chg_1 { text "Xerxes, greife an." }
	sub sd1chg_2 { text "Aktiviere Kampfprogramm. Bitte um Best„tigung." }
	sub sd1chg_3 { text "Xerxes, greife Eindringling an." }
	sub sd1hhi_1 { text "Xerxes, Einheit wird angegriffen." }
	sub sd1hhi_2 { text "Xerxes, Waffen im Anflug." }
	sub sd1hhi_3 { text "Feind in Gebiet." }
	sub sd1los_1 { text "Xerxes, andere Einheiten verst„ndigen. Eindringling verschwunden." }
	sub sd1los_2 { text "Xerxes, Ziel verschwunden." }
	sub sd1los_3 { text "Xerxes, kann Eindringling nicht lokalisieren." }
	sub sd1los_4 { text "Xerxes, Eindringling wurde noch nicht gefasst." }
	sub sd1los_5 { text "Eindringling ist entkommen." }
	sub sd1to1_1 { text "Xerxes, Anomalie entdeckt." }
	sub sd1to1_2 { text "Xerxes, verstanden. Wird untersucht." }
	sub sd1to1_3 { text "Xerxes, befinden sich andere Einheiten in diesem Gebiet?" }
	sub sd1to1_4 { text "Sekund„rerfassungsmodus aktiviert, Xerxes." }
	sub sd1to1_5 { text "Xerxes, unbekannter Input." }
	sub sd1to2_1 { text "Xerxes, Sensoren melden ungew”hnliche Aktivit„t." }
	sub sd1to2_2 { text "Sekund„rsensoren haben etwas entdeckt, Xerxes." }
	sub sd1to2_3 { text "Xerxes, m”gliches Ziel." }
	sub sd1to2_4 { text "Xerxes, Eindringen best„tigt." }
	sub sd1to2_5 { text "Xerxes, m”glicherweise feindliche Einheit." }
	sub sd1to3_1 { text "Xerxes, Eindringling eindeutig identifiziert." }
	sub sd1to3_2 { text "Eindringling. Wiederhole, Eindringling." }
	sub sd1to3_3 { text "Xerxes, Eindringen eindeutig festgestellt." }
	sub sd1to3_4 { text "Xerxes, visuelle Best„tigung." }
	sub sd1to3_5 { text "Xerxes, Eindringling wurde erfasst." }
}

{
	type "nonverbal"
	descr "Bot"
	sub dr1at0_1 { text "[inaktiv]" }
	sub dr1at0_2 { text "[inaktiv]" }
	sub dr1at0_3 { text "[inaktiv]" }
	sub dr1at0_4 { text "[inaktiv]" }
	sub dr1at0_5 { text "[inaktiv]" }
	sub dr1at0_6 { text "[inaktiv]" }
	sub dr1at1_1 { text "[wachsam]" }
	sub dr1at1_2 { text "[wachsam]" }
	sub dr1at1_3 { text "[wachsam]" }
	sub dr1at1_4 { text "[wachsam]" }
	sub dr1at1_5 { text "[wachsam]" }
	sub dr1at1_6 { text "[wachsam]" }
	sub dr1at2_1 { text "[sucht]" }
	sub dr1at2_2 { text "[sucht]" }
	sub dr1at2_3 { text "[sucht]" }
	sub dr1at2_4 { text "[sucht]" }
	sub dr1at2_5 { text "[sucht]" }
	sub dr1at2_6 { text "[sucht]" }
	sub dr1at2_7 { text "[sucht]" }
	sub dr1at2_8 { text "[sucht]" }
	sub fdrospa4 { text "[feuert Blitz]" }
	sub fdrospa5 { text "[feuert Blitz]" }
	sub fdrofus1 { text "[feuert Fusionskanone]" }
	sub fdrofus2 { text "[feuert Fusionskanone]" }
	sub fdrofus3 { text "[feuert Fusionskanone]" }
	sub fdrolas1 { text "[feuert Laser]" }
	sub fdrolas2 { text "[feuert Laser]" }
	sub fdrolas3 { text "[feuert Laser]" }
	sub md1die_1 { text "[stirbt]" }
	sub md1die_2 { text "[stirbt]" }
	sub md1hhi_1 { text "[besch„digt]" }
	sub md1hhi_2 { text "[besch„digt]" }
	sub md1hhi_3 { text "[besch„digt]" }
	sub md1hhi_4 { text "[besch„digt]" }
	sub md1hlo_1 { text "[besch„digt]" }
	sub md1hlo_2 { text "[besch„digt]" }
	sub md1hlo_3 { text "[besch„digt]" }
	sub md1hlo_4 { text "[besch„digt]" }
	sub sd1hhi_4 { text "[besch„digt]" }
	sub sd1hhi_5 { text "[besch„digt]" }
	sub sd1hhi_6 { text "[besch„digt]" }
	sub sd1hlo_1 { text "[besch„digt]" }
	sub sd1hlo_2 { text "[besch„digt]" }
	sub sd1hlo_3 { text "[besch„digt]" }
	sub sd1hlo_4 { text "[besch„digt]" }
}
