SUB1

{
	type "nonverbal"
	descr "Rumbler"
	sub rm1at0_1 { text "[inaktiv]" } // AI_AT0, AI_BAK
	sub rm1at0_2 { text "[inaktiv]" } // AI_AT0, AI_BAK
	sub rm1at0_3 { text "[inaktiv]" } // AI_AT0
	sub rm1at0_4 { text "[inaktiv]" } // AI_AT0
	sub rm1at0_5 { text "[inaktiv]" } // AI_AT0, AI_LOS
	sub rm1at2_1 { text "[sucht]" } // AI_AT2, AI_AT3
	sub rm1at2_2 { text "[sucht]" } // AI_AT2, AI_AT3
	sub rm1at2_3 { text "[sucht]" } // AI_AT2
	sub rm1at2_4 { text "[sucht]" } // AI_AT2
	sub rm1chg_1 { text "[greift an]" } // AI_CHG
	sub rm1chg_2 { text "[greift an]" } // AI_CHG
	sub rm1chg_3 { text "[greift an]" } // AI_ATT
	sub rm1die_1 { text "[Todesschrei]" } // AI_DIE
	sub rm1die_2 { text "[Todesschrei]" } // AI_DIE
	sub rm1hhi_1 { text "[Brüllen]" } // AI_ATT, AI_HHI
	sub rm1to1_1 { text "[wachsam]" } // AI_TO1
	sub rm1to1_2 { text "[wachsam]" } // AI_TO1
	sub rm1to3_1 { text "[Brüllen]" } // AI_TO3, AI_AT3
	sub rm1to3_2 { text "[Brüllen]" } // AI_TO3, AI_AT3, AI_ATT
	sub rm1to3_3 { text "[Brüllen]" } // AI_ATT
}
